version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: laurenong/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: laurenong/education-space
          # tag: v1.0.1
      - docker/push:
          image: laurenong/education-space
          # tag: v1.0.1

  deploy:
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
              heroku container:login
              heroku container:push web -a lauren-su-devops
              heroku container:release web -a lauren-su-devops

  # pull-and-deploy:
  #   docker:
  #     - image:cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install
  #     - docker/pull:
  #         images: laurenong/education-space:v1.0.1
  #     - run:
  #         name: Heroku Container Push With Image From Docker Hub
  #         command: |
  #           heroku container:login
  #           docker tag laurenong/education-space:v1.0.1 registry.heroku.com/lauren-su-devops/web
  #           # format docker tag <image name from docker hub> registry.heroku.com/<app-name>/web
  #           docker push registry.heroku.com/lauren-su-devops/web
  #           # docker push registry.heroku.com.<app-name>
  #           heroku container:release web -a lauren-su-devops

# workflows:
#   notsimple_workflow:
#     jobs:
#       - build:
#         filters:
#           branches:
#             only:
#               - main
#               - release
#       - test:
#         filters:
#           branches:
#             only:
#               - main
#               - release
#           requires:
#             - build
#       - publish:
#         filters:
#           branches:
#             only:
#               - release
#           requires:
#             # - test
#             - build
#       - deploy:
#         filters:
#           branches:
#             only:
#               - release
#           requires:
#             # - publish
#             - build




# workflows:
#   simple_workflow:
#     jobs:
#       - build:
#       - test:
#           requires:
#             - build
#       - publish:
#           requires:
#             # - test
#             - build
#       - deploy:
#           requires:
#             # - publish
#             - build


workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
      - publish:
          requires:
            - scan